# --- Stage 1: Build app ---
    FROM node:20-alpine AS builder
    WORKDIR /app
    
    COPY package*.json ./
    RUN npm install
    COPY . .
    RUN npm run build
    
    # --- Stage 2: Run app ---
    FROM node:20-alpine
    WORKDIR /app
    
    COPY --from=builder /app ./
    EXPOSE 3000
    CMD ["npm", "start"]
    